server:
  port: 8000  # 定义单点登录端口，修改1
  servlet:    context-path: /   # 该配置可以删除，默认配置就是"/"
spring:  datasource:
    #引入druid数据源
    type: com.alibaba.druid.pool.DruidDataSource    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/jtdb?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
    username: root
    password: root
  application:   #定义服务名称，【】注意层级！这里要缩进
    name: provider-user # 服务名称，修改3，整个服务的id，这句和下面的相当于注册服务
    
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7000/eureka
  instance:
    instance-id: provider-user-8000    #定义微服务的名称，修改4，具体id
    prefer-ip-address: true                        #是否显示IP和端口


#mybatis-plus配置
mybatis-plus:
  type-aliases-package: com.jt.provider.pojo # 修改2
  mapper-locations: classpath:/mybatis/mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true  #自动开启驼峰规则映射